# .github/workflows/build.yml
name: Code Analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  snyk:
    name: Snyk Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instalar solo Snyk CLI (sin dependencias de Python)
      - name: Setup Snyk
        uses: snyk/actions/setup@master

      # Escaneo de código exclusivo (ignora venv/ y dependencias)
      - name: Run Snyk Code Scan
        run: |
          snyk code test \
            --severity-threshold=high \
            --exclude=venv/**,**/__pycache__/**,**/*.pyc \
            --json-file-output=snyk_code_results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Opcional: Sube resultados como artefacto
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snyk-code-report
          path: snyk_code_results.json