# .github/workflows/build.yml
name: Code Analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  snyk:
    name: Snyk Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Snyk
        uses: snyk/actions/setup@master
      - name: Run Snyk Scan
        run: |
          snyk code test --severity-threshold=high --json > snyk_report.json || true
          cat snyk_report.json  # Esto mostrará el reporte en los logs
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-report
          path: snyk_report.json

  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/r2c-security-audit  # Reglas de seguridad recomendadas
          # Opcional: Excluir venv/ y otros
          exclude: venv/,__pycache__/
        env:
          SEMGREP_RULES: p/r2c-security-audit  # Reglas específicas

  # snyk:
  #   name: Snyk Code Analysis
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Snyk
  #       uses: snyk/actions/setup@master
  #     - name: Run Snyk
  #       run: snyk code test --severity-threshold=high
  #       env:
  #         SNYK_TOKEN: 