# File: .github/workflows/code-quality.yml

name: CI - Python Quality Check

on:
  push:
    branches:
      - '**'

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install SonarCloud Scanner
      run: |
        pip install sonar-scanner-cli

    - name: SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=<TU_PROYECTO_SONARCLOUD> \
          -Dsonar.organization=<TU_ORGANIZACION_SONARCLOUD> \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      continue-on-error: true

    - name: Install Snyk
      run: |
        npm install -g snyk

    - name: Auth Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk auth $SNYK_TOKEN

    - name: Run Snyk to check for vulnerabilities
      run: |
        snyk test --all-projects || true
      continue-on-error: true

    - name: Upload Snyk Report (Optional)
      if: always()
      run: echo "Snyk scan completed."

    - name: Upload SonarCloud Report (Optional)
      if: always()
      run: echo "SonarCloud analysis completed."
