# File: .github/workflows/code-quality.yml

name: CI - Python Quality Check

on:
  push:
    branches:
      - master

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Snyk - Install
      run: npm install -g snyk

    - name: Snyk - Authenticate
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Snyk - Test for vulnerabilities
      run: snyk test --all-projects || true
      continue-on-error: true

    - name: SonarCloud - Scan
      uses: SonarSource/sonarcloud-github-action@v2.0.2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
