name: Semgrep Scan

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  semgrep-scan:
    name: Run Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep Scan
        run: semgrep scan --config auto --json --quiet
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}